## Симплекс метод

In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
import random 

In [2]:
def matrix_gen (m,n,basis): # функция для генерации матрицы [m, n]
    A = np.zeros((m, n)) # итоговая матрица для работы метода
    col_zer = 0
    for i in range(m):
        for j in range(n):
            if i==0:
                A[i,j] = random.randint(-50, 10) 
            else:
                A[i,j] = random.randint(-50, 100) 
            
    A[0,n-1] = 0
    for i in range(len(basis)):
        stb = basis[i]-1
        for j in range(m):
            if j==i+1:
                A[j,stb] = 1
            else:
                A[j, stb] = 0
        
    return A
    

In [3]:
def admis(A):  # проверка на то, является ли матрица двойственно допустимой
    k, l = A.shape
    fl = True
    E = 0.0001
    for i in range(l-1):
        if A[0,i] + E <0:
            fl = False
    return fl

In [4]:
def find_c(A): # поиск ведущего столбца
    k, l = A.shape
    minim = 1
    nom = -1
    for i in range(l-1):
        if A[0,i]< minim:
            minim = A[0,i]
            nom = i
    return nom

In [5]:
def find_l(A,j):  # поиск ведущей строки
    k, l = A.shape
    nom = -1
    for i in range(1,k):
        if  (A[i,j] != 0 ) and (A[i,l-1]/A[i,j])>0:
            if nom==-1:
                fl = A[i,l-1]/A[i,j]
                nom = i
            elif A[i,l-1]/A[i,j] < fl:
                fl = A[i,l-1]/A[i,j]
                nom = i
   
    return nom

In [6]:
def change(A,i,j): # преобразовываем таблицу по Гауссу
    m, n = A.shape
    delit = 1/A[i,j]
    for p in range(n): # преобразовали строку
        A[i,p] = A[i,p] * delit 
    
    for t in range(m):
        mn = A[t,j] * (-1)
        if t!=i:
            for p in range(n):
                A[t,p] = A[t,p] + A[i,p] * mn
    return A
            
    

In [7]:
def exm(A,basis): # проверка на существование решения
    m, n = A.shape
    fl_1 = True # решения существует
    for i in range(1,m):
        fl = True # для конкретной строки
        nom = basis[i-1]
        for j in range(n-1):
            if (j != nom-1) and (A[i,j]<0):
                fl = False
                
        if (fl==True) and (A[i,n-1]<0):
            fl_1 = False
    return fl_1

Постановка задачи:

In [15]:
n = random.randint(3, 100) # кол-во столбцов матрицы (общее количество переменных + 1 стб)
m = random.randint(3, 100) # кол-во строк матрицы (кол-во базисных переменных + 1 стр)

if n<=m:
    if n == m:
        m = m-1
    else:
        n, m = m, n
print("Размерность будущей матрицы: ", m,n)

#variables = ['x'+str(i) for i in range(1,n)]
variables = [i for i in range(1,n)]
basis = np.random.choice(variables, m-1, replace = False)

print("Размер исходный базиса:", len(basis))
print("Исходный базис:", basis)

A = matrix_gen (m,n,basis) # сгенерировали матрицу 
print(A)

Размерность будущей матрицы:  73 87
Размер исходный базиса: 72
Исходный базис: [16 82 29 55 51 78 22 28 24 64 46 72 17 67 68 66 42 44  4 77 32 60 37 12
 69 10 33 58 57  9 23 39 81  2 59 80  3 14 13 21 83 76 25 63 61 73 62 65
 11  5 35 85 75  1 45  7 27 31 84 19 30 79 26 40  6 71  8 18 50 41 15 34]
[[  0.   0.   0. ...   0. -48.   0.]
 [  0.   0.   0. ...   0. 100.  -9.]
 [  0.   0.   0. ...   0.  49.  78.]
 ...
 [  0.   0.   0. ...   0.   1. -11.]
 [  0.   0.   0. ...   0.  19.  96.]
 [  0.   0.   0. ...   0.  -3.  94.]]


In [16]:
fl =  admis(A)
while fl == False:
    if exm(A,basis)==False:
        print("Задача не имеет решения")
        break
    stb = find_c(A) # ведущий столбец
    print(stb)
    st = find_l(A,stb) # ведущая строка
    print(st)
    if st == -1:
        print("Функция неограниченно возрастает")
        break
    basis[st-1] = variables[stb] # поменяли базис
    A = change(A,st,stb) # поменяли матрицу
    print(A)
    print("Базис:",basis )
    print("----------------")
    fl =  admis(A)


85
12
[[  0.           0.           0.         ...   0.           0.
    4.04210526]
 [  0.           0.           0.         ...   0.           0.
  -17.42105263]
 [  0.           0.           0.         ...   0.           0.
   73.87368421]
 ...
 [  0.           0.           0.         ...   0.           0.
  -11.08421053]
 [  0.           0.           0.         ...   0.           0.
   94.4       ]
 [  0.           0.           0.         ...   0.           0.
   94.25263158]]
Базис: [16 82 29 55 51 78 22 28 24 64 46 86 17 67 68 66 42 44  4 77 32 60 37 12
 69 10 33 58 57  9 23 39 81  2 59 80  3 14 13 21 83 76 25 63 61 73 62 65
 11  5 35 85 75  1 45  7 27 31 84 19 30 79 26 40  6 71  8 18 50 41 15 34]
----------------
53
46
[[  0.           0.           0.         ...   0.           0.
    4.42483221]
 [  0.           0.           0.         ...   0.           0.
  -18.21532438]
 [  0.           0.           0.         ...   0.           0.
   73.21767338]
 ...
 [  0.           0.   

In [17]:
print("Значения: ")
for i in range(len(basis)):
    print("x", basis[i], "=", A[i+1,n-1])
print("Максимальное значение функции: ", A[0,n-1])

Значения: 
x 16 = -10.418507159141583
x 82 = 76.47893290865302
x 43 = 0.031969526970409765
x 36 = 0.014100812939338424
x 51 = 79.51787065669318
x 78 = -12.439137259439073
x 22 = -26.395821290626994
x 28 = 96.4916941481405
x 24 = -14.583824143318385
x 64 = -42.14709157579685
x 46 = 24.589754227340688
x 55 = 1.006863964869759
x 17 = -33.015468447066134
x 67 = 2.0366173460731636
x 68 = 62.53245540834973
x 66 = 20.487710071925974
x 42 = 2.873154417030841
x 44 = 11.491810599941543
x 4 = 51.067863555183926
x 77 = 85.18560215402375
x 32 = 6.330776538167485
x 60 = 29.627507922823643
x 37 = 38.34751375944404
x 12 = 43.71065094722046
x 69 = 18.020637115466215
x 74 = 0.19974419457012993
x 33 = 22.240280429751394
x 58 = 19.34529513138655
x 57 = 34.085986110397606
x 9 = 68.36214491913991
x 23 = -28.17207885136001
x 39 = 30.358301254225832
x 81 = 65.39285290292001
x 2 = 76.45789387798094
x 59 = 6.961153665004754
x 80 = 67.38943975351505
x 3 = 81.43251882547511
x 14 = 17.56660708450019
x 13 = -60.041

Проверка:

In [11]:
A = np.array([[-2., -3., 0., 0., 0.],
    [2., 1., 1., 0., 4.],
    [1., 2., 0., 1., 5.]])
m,n = A.shape
variables = [1, 2, 3, 4]
basis = [3, 4]

fl =  admis(A)
while fl == False:
    if exm(A,basis)==False:
        print("Задача не имеет решения")
        break
    stb = find_c(A) # ведущий столбец
    print(stb)
    st = find_l(A,stb) # ведущая строка
    print(st)
    if st == -1:
        print("Функция неограниченно возрастает")
        break
    basis[st-1] = variables[stb] # поменяли базис
    A = change(A,st,stb) # поменяли матрицу
    print(A)
    print("Базис:",basis )
    print("----------------")
    fl =  admis(A)


1
2
[[-0.5  0.   0.   1.5  7.5]
 [ 1.5  0.   1.  -0.5  1.5]
 [ 0.5  1.   0.   0.5  2.5]]
Базис: [3, 2]
----------------
0
1
[[ 0.          0.          0.33333333  1.33333333  8.        ]
 [ 1.          0.          0.66666667 -0.33333333  1.        ]
 [ 0.          1.         -0.33333333  0.66666667  2.        ]]
Базис: [1, 2]
----------------


In [12]:
print("Значения: ")
m, n = A.shape
for i in range(len(basis)):
    print("x",basis[i], "=", A[i+1,n-1])
print("Максимальное значение функции: ", A[0,n-1])

Значения: 
x 1 = 1.0
x 2 = 2.0
Максимальное значение функции:  8.0


Если функция неограниченно возрастает:

In [13]:
A = np.array([[-1., -2., 0., 0., 0.],
    [-2., 3., 1., 0., 9.],
    [1., -2., 0., 1., 2.]])
m,n = A.shape
variables = [1, 2, 3, 4]
basis = [3,4]

fl =  admis(A)
while fl == False:
    if exm(A,basis)==False:
        print("Задача не имеет решения")
        break
    stb = find_c(A) # ведущий столбец
    print(stb)
    st = find_l(A,stb) # ведущая строка
    print(st)
    if st == -1:
        print("Функция неограниченно возрастает")
        break
    basis[st-1] = variables[stb] # поменяли базис
    A = change(A,st,stb) # поменяли матрицу
    print(A)
    print("Базис:",basis )
    print("----------------")
    fl =  admis(A)


1
1
[[-2.33333333  0.          0.66666667  0.          6.        ]
 [-0.66666667  1.          0.33333333  0.          3.        ]
 [-0.33333333  0.          0.66666667  1.          8.        ]]
Базис: [2, 4]
----------------
0
-1
Функция неограниченно возрастает


Если задача не имеет решения:


In [14]:
A = np.array([[-1., 1., 0., 0., 0., 0.],
    [2., -3., 1., 0., 0., -9.],
    [-1., 2., 0., 1., 0., -2.],
    [1., 1., 0., 0., 1., 8.]])
m,n = A.shape
variables = [1, 2, 3, 4, 5]
basis = [3,4, 5]

fl =  admis(A)
while fl == False:
    if exm(A,basis)==False:
        print("Задача не имеет решения")
        break
    stb = find_c(A) # ведущий столбец
    print(stb)
    st = find_l(A,stb) # ведущая строка
    print(st)
    if st == -1:
        print("Функция неограниченно возрастает")
        break
    basis[st-1] = variables[stb] # поменяли базис
    A = change(A,st,stb) # поменяли матрицу
    print(A)
    print("Базис:",basis )
    print("----------------")
    fl =  admis(A)


0
2
[[  0.  -1.   0.  -1.   0.   2.]
 [  0.   1.   1.   2.   0. -13.]
 [  1.  -2.  -0.  -1.  -0.   2.]
 [  0.   3.   0.   1.   1.   6.]]
Базис: [3, 1, 5]
----------------
Задача не имеет решения
